import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import PageHeader from '../../../components/common/PageHeader'
import EmptyState from '../../../components/feedback/EmptyState'
import ErrorState from '../../../components/feedback/ErrorState'
import PageLoader from '../../../components/feedback/PageLoader'
import AppInput from '../../../components/forms/AppInput'
import AppSelect from '../../../components/forms/AppSelect'
import Pagination from '../../publicJobs/components/Pagination'
import { getApiErrorMessage } from '../../../api/errorMapper'
import { formatDateTime } from '../../../utils/date'
import AdminStatusBadge from '../components/AdminStatusBadge'
import { AUDIT_ACTIONS, AUDIT_ACTOR_ROLES, AUDIT_RESOURCE_TYPES, humanize } from '../constants/adminModerationConstants'
import { adminApi } from '../services/adminApi'

function AdminAuditLogsPage(){
 const [params,setParams]=useSearchParams(); const page=Number(params.get('page')||1); const actorRole=params.get('actorRole')||''; const action=params.get('action')||''; const resourceType=params.get('resourceType')||''; const resourceId=params.get('resourceId')||''; const actorId=params.get('actorId')||''; const from=params.get('from')||''; const to=params.get('to')||''; const query=useMemo(()=>({page,actorRole,action,resourceType,resourceId,actorId,from,to}),[page,actorRole,action,resourceType,resourceId,actorId,from,to]); const [draft,setDraft]=useState(query); const [state,setState]=useState({auditLogs:[],pagination:null,loading:true,error:null})
 const load=useCallback(async(signal)=>{await Promise.resolve();setState(s=>({...s,loading:true,error:null}));try{const result=await adminApi.listAuditLogs(query,signal);setState({...result,loading:false,error:null})}catch(error){if(error?.name!=='CanceledError'&&error?.code!=='ERR_CANCELED')setState({auditLogs:[],pagination:null,loading:false,error})}},[query])
 useEffect(()=>{const c=new AbortController();load(c.signal);return()=>c.abort()},[load])
 const apply=e=>{e.preventDefault();const n=new URLSearchParams();for(const [k,v] of Object.entries(draft)){if(k!=='page'&&String(v||'').trim())n.set(k,String(v).trim())}n.set('page','1');setParams(n)}
 return <div className="space-y-6"><PageHeader title="Audit logs" description="Read-only investigation view using server-side actor, action, resource, date and pagination filters."/><form onSubmit={apply} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-4"><div><label className="mb-1 block text-sm font-semibold" htmlFor="audit-action">Action</label><AppSelect id="audit-action" value={draft.action} onChange={e=>setDraft({...draft,action:e.target.value})}><option value="">All actions</option>{AUDIT_ACTIONS.map(v=><option key={v} value={v}>{humanize(v)}</option>)}</AppSelect></div><div><label className="mb-1 block text-sm font-semibold" htmlFor="audit-role">Actor role</label><AppSelect id="audit-role" value={draft.actorRole} onChange={e=>setDraft({...draft,actorRole:e.target.value})}><option value="">All roles</option>{AUDIT_ACTOR_ROLES.map(v=><option key={v} value={v}>{humanize(v)}</option>)}</AppSelect></div><div><label className="mb-1 block text-sm font-semibold" htmlFor="audit-resource">Resource type</label><AppSelect id="audit-resource" value={draft.resourceType} onChange={e=>setDraft({...draft,resourceType:e.target.value})}><option value="">All resources</option>{AUDIT_RESOURCE_TYPES.map(v=><option key={v} value={v}>{humanize(v)}</option>)}</AppSelect></div><div><label className="mb-1 block text-sm font-semibold" htmlFor="audit-resource-id">Resource ID</label><AppInput id="audit-resource-id" value={draft.resourceId} onChange={e=>setDraft({...draft,resourceId:e.target.value})}/></div><div><label className="mb-1 block text-sm font-semibold" htmlFor="audit-actor-id">Actor ID</label><AppInput id="audit-actor-id" value={draft.actorId} onChange={e=>setDraft({...draft,actorId:e.target.value})}/></div><div><label className="mb-1 block text-sm font-semibold" htmlFor="audit-from">From</label><AppInput id="audit-from" type="datetime-local" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></div><div><label className="mb-1 block text-sm font-semibold" htmlFor="audit-to">To</label><AppInput id="audit-to" type="datetime-local" value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></div><div className="flex items-end gap-2"><button className="rounded-lg bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white" type="submit">Apply</button><button className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold" type="button" onClick={()=>{const clean={page:1,actorRole:'',action:'',resourceType:'',resourceId:'',actorId:'',from:'',to:''};setDraft(clean);setParams({page:'1'})}}>Clear</button></div></form>
 {state.loading?<PageLoader label="Loading audit logs"/>:state.error?<ErrorState message={getApiErrorMessage(state.error)} onRetry={()=>load()}/>:state.auditLogs.length===0?<EmptyState title="No audit logs found" description="No audit records match the selected backend filters."/>:<><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Timestamp</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Actor</th><th className="px-4 py-3">Resource</th><th className="px-4 py-3">Result</th><th className="px-4 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{state.auditLogs.map(a=><tr key={a.id}><td className="px-4 py-3">{formatDateTime(a.createdAt)}</td><td className="px-4 py-3">{humanize(a.action)}</td><td className="px-4 py-3">{humanize(a.actorRole)}<p className="text-xs text-slate-500">{a.actorUserId||'System'}</p></td><td className="px-4 py-3">{humanize(a.resourceType)}<p className="text-xs text-slate-500">{a.resourceId||'—'}</p></td><td className="px-4 py-3"><AdminStatusBadge status={a.result}/></td><td className="px-4 py-3"><Link className="font-semibold text-brand-700 hover:underline" to={`/admin/audit-logs/${a.id}`}>View details</Link></td></tr>)}</tbody></table></div><Pagination pagination={state.pagination} onPageChange={p=>{const n=new URLSearchParams(params);n.set('page',String(p));setParams(n)}}/></>}
 </div>
}
export default AdminAuditLogsPage
